export const ACHIEVEMENT_TIERS = {
  BRONZE: {
    color: '#CD7F32',
    shadowColor: '#8B5A2B',
    borderColor: '#E6A85C',
  },
  SILVER: {
    color: '#C0C0C0',
    shadowColor: '#808080',
    borderColor: '#E8E8E8',
  },
  GOLD: {
    color: '#FFD700',
    shadowColor: '#B8860B',
    borderColor: '#FFED4E',
  },
};

export const ACHIEVEMENTS = [
  {
    id: "streak-3",
    title: "Getting Started",
    description: "Complete tasks for 3 days in a row",
    requirement: 3,
    type: "streak",
    icon: "flame",
    color: "#FF6B6B",
    tier: "BRONZE",
  },
  {
    id: "total-10",
    title: "Task Tackler",
    description: "Complete 10 total tasks",
    requirement: 10,
    type: "total",
    icon: "target",
    color: "#10B981",
    tier: "BRONZE",
  },
  {
    id: "streak-7",
    title: "Week Warrior",
    description: "Complete tasks for 7 days straight",
    requirement: 7,
    type: "streak",
    icon: "trophy",
    color: "#FFD700",
    tier: "SILVER",
  },
  {
    id: "longest-14",
    title: "Consistency Champion",
    description: "Achieve a 14-day streak",
    requirement: 14,
    type: "longest",
    icon: "zap",
    color: "#8B5CF6",
    tier: "SILVER",
  },
  {
    id: "total-50",
    title: "Productivity Pro",
    description: "Complete 50 total tasks",
    requirement: 50,
    type: "total",
    icon: "star",
    color: "#F59E0B",
    tier: "GOLD",
  },
  {
    id: "streak-30",
    title: "Monthly Master",
    description: "Maintain a 30-day streak",
    requirement: 30,
    type: "streak",
    icon: "award",
    color: "#5B5FDE",
    tier: "GOLD",
  },
];